// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/27/2025, 00:09:03
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/plugins/**/*.{js,ts,mjs}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/composables/**/*.{js,ts,mjs}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/utils/**/*.{js,ts,mjs}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ade.iskandar/Desktop/Epsilla Prompt/sourcecode-WAMarketing-dashboard/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;