
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'PaymentModal': typeof import("../components/PaymentModal.vue")['default']
    'AuthLoginForm': typeof import("../components/auth/LoginForm.vue")['default']
    'AuthRegisterForm': typeof import("../components/auth/RegisterForm.vue")['default']
    'DashboardAdminStats': typeof import("../components/dashboard/AdminStats.vue")['default']
    'DashboardMessageHistory': typeof import("../components/dashboard/MessageHistory.vue")['default']
    'DashboardUserStats': typeof import("../components/dashboard/UserStats.vue")['default']
    'MessagesBulkMessageSender': typeof import("../components/messages/BulkMessageSender.vue")['default']
    'MessagesBulkProgress': typeof import("../components/messages/BulkProgress.vue")['default']
    'MessagesMessageComposer': typeof import("../components/messages/MessageComposer.vue")['default']
    'MessagesMessageFormatBar': typeof import("../components/messages/MessageFormatBar.vue")['default']
    'MessagesMessageSender': typeof import("../components/messages/MessageSender.vue")['default']
    'PlansPaymentForm': typeof import("../components/plans/PaymentForm.vue")['default']
    'PlansPlanCard': typeof import("../components/plans/PlanCard.vue")['default']
    'WhatsappBindSession': typeof import("../components/whatsapp/BindSession.vue")['default']
    'WhatsappSessionManager': typeof import("../components/whatsapp/SessionManager.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyPaymentModal': typeof import("../components/PaymentModal.vue")['default']
    'LazyAuthLoginForm': typeof import("../components/auth/LoginForm.vue")['default']
    'LazyAuthRegisterForm': typeof import("../components/auth/RegisterForm.vue")['default']
    'LazyDashboardAdminStats': typeof import("../components/dashboard/AdminStats.vue")['default']
    'LazyDashboardMessageHistory': typeof import("../components/dashboard/MessageHistory.vue")['default']
    'LazyDashboardUserStats': typeof import("../components/dashboard/UserStats.vue")['default']
    'LazyMessagesBulkMessageSender': typeof import("../components/messages/BulkMessageSender.vue")['default']
    'LazyMessagesBulkProgress': typeof import("../components/messages/BulkProgress.vue")['default']
    'LazyMessagesMessageComposer': typeof import("../components/messages/MessageComposer.vue")['default']
    'LazyMessagesMessageFormatBar': typeof import("../components/messages/MessageFormatBar.vue")['default']
    'LazyMessagesMessageSender': typeof import("../components/messages/MessageSender.vue")['default']
    'LazyPlansPaymentForm': typeof import("../components/plans/PaymentForm.vue")['default']
    'LazyPlansPlanCard': typeof import("../components/plans/PlanCard.vue")['default']
    'LazyWhatsappBindSession': typeof import("../components/whatsapp/BindSession.vue")['default']
    'LazyWhatsappSessionManager': typeof import("../components/whatsapp/SessionManager.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const PaymentModal: typeof import("../components/PaymentModal.vue")['default']
export const AuthLoginForm: typeof import("../components/auth/LoginForm.vue")['default']
export const AuthRegisterForm: typeof import("../components/auth/RegisterForm.vue")['default']
export const DashboardAdminStats: typeof import("../components/dashboard/AdminStats.vue")['default']
export const DashboardMessageHistory: typeof import("../components/dashboard/MessageHistory.vue")['default']
export const DashboardUserStats: typeof import("../components/dashboard/UserStats.vue")['default']
export const MessagesBulkMessageSender: typeof import("../components/messages/BulkMessageSender.vue")['default']
export const MessagesBulkProgress: typeof import("../components/messages/BulkProgress.vue")['default']
export const MessagesMessageComposer: typeof import("../components/messages/MessageComposer.vue")['default']
export const MessagesMessageFormatBar: typeof import("../components/messages/MessageFormatBar.vue")['default']
export const MessagesMessageSender: typeof import("../components/messages/MessageSender.vue")['default']
export const PlansPaymentForm: typeof import("../components/plans/PaymentForm.vue")['default']
export const PlansPlanCard: typeof import("../components/plans/PlanCard.vue")['default']
export const WhatsappBindSession: typeof import("../components/whatsapp/BindSession.vue")['default']
export const WhatsappSessionManager: typeof import("../components/whatsapp/SessionManager.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyPaymentModal: typeof import("../components/PaymentModal.vue")['default']
export const LazyAuthLoginForm: typeof import("../components/auth/LoginForm.vue")['default']
export const LazyAuthRegisterForm: typeof import("../components/auth/RegisterForm.vue")['default']
export const LazyDashboardAdminStats: typeof import("../components/dashboard/AdminStats.vue")['default']
export const LazyDashboardMessageHistory: typeof import("../components/dashboard/MessageHistory.vue")['default']
export const LazyDashboardUserStats: typeof import("../components/dashboard/UserStats.vue")['default']
export const LazyMessagesBulkMessageSender: typeof import("../components/messages/BulkMessageSender.vue")['default']
export const LazyMessagesBulkProgress: typeof import("../components/messages/BulkProgress.vue")['default']
export const LazyMessagesMessageComposer: typeof import("../components/messages/MessageComposer.vue")['default']
export const LazyMessagesMessageFormatBar: typeof import("../components/messages/MessageFormatBar.vue")['default']
export const LazyMessagesMessageSender: typeof import("../components/messages/MessageSender.vue")['default']
export const LazyPlansPaymentForm: typeof import("../components/plans/PaymentForm.vue")['default']
export const LazyPlansPlanCard: typeof import("../components/plans/PlanCard.vue")['default']
export const LazyWhatsappBindSession: typeof import("../components/whatsapp/BindSession.vue")['default']
export const LazyWhatsappSessionManager: typeof import("../components/whatsapp/SessionManager.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
